### ISSUE TITLE
NoClassDefFoundError: edu/stanford/nlp/pipeline/StanfordCoreNLP

### ISSUE THREAD

**Issue by bigstas** [toliwa/CoreNLP-jMWE#2]
I ran the demo. This is what I get:

`~/Software/stanford core NLP MWE annotator# ./runJMWEDemo.sh "She traveled to Las Vegas and looked up the world record."
Running edu.stanford.nlp.pipeline.demo.JMWEAnnotatorDemo with input text. The input should be enclosed in " " symbols, example usage:  $ ./runJMWEDemo.sh "She looked up the world record."
Exception in thread "main" java.lang.NoClassDefFoundError: edu/stanford/nlp/pipeline/StanfordCoreNLP
	at edu.stanford.nlp.pipeline.demo.JMWEAnnotatorDemo.jmweDemo(JMWEAnnotatorDemo.java:53)
	at edu.stanford.nlp.pipeline.demo.JMWEAnnotatorDemo.main(JMWEAnnotatorDemo.java:36)
Caused by: java.lang.ClassNotFoundException: edu.stanford.nlp.pipeline.StanfordCoreNLP
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:582)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:190)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:499)
	... 2 more`

- the classpath in runJMWEDemo.sh is `./*:lib/* edu.stanford.nlp.pipeline.demo.JMWEAnnotatorDemo`, so this should refer to the folder in which the script is run
- I have both the `stanford-corenlp-jmwe-annotator.jar` file and the expanded version (`edu` folder and its children) in the folder where the script is run
- I've tried altering the classpath but to no effect (and surely the `-cp` flag should be specifying the relevant classpath anyway?)
- when I write my own Java file in this folder and import this class, I don't get this error

Please bear in mind that I'm new to Java so there might be something that I'm missing because of that.

**Comment by toltoxgh** [comment]
The line ```Caused by: java.lang.ClassNotFoundException: edu.stanford.nlp.pipeline.StanfordCoreNLP``` shows what the problem is. 

You need to download the CoreNLP jars (and the model jar) from the CoreNLP page and put them into the ```lib/*``` folder, where the script can find them.

**Comment by bigstas** [comment]
Thanks a lot! I know my issue was quite basic, but it was really helpful that you got back to me on that.

To clarify in case anybody else gets this error:
- Stanford Core NLP has a whole bunch of .jar files in it
- you need to put them in your_project/lib
- make sure you also put mweindex_wordnet3.0_semcor1.6.data in your_project/lib

Then it works! Hurray!
